### ISSUE TITLE
请教一下，关于Two_stage_TrAdaboost_R2中exp6的内容

### ISSUE THREAD

**Issue by qinhaohcen** [Bin-Cao/TrAdaboost#2]
exp6中所使用的源域和目标域数据都是一一对应的，而实际问题中，可能存在多对一的情况。Two_stage_TrAdaboost_R2函数可否解决多对一的情况呢？

**Comment by Bin-Cao** [comment]
您指的情况是：
(1）同一数据进行多次测量（ 相同x,不同y)
(2)  不同数据的表征性能相同（不同x, 相同y) 
(3)  数据无法区分是源域数据还是目标数据 
以上哪种情况呢？

**Comment by qinhaohcen** [comment]
我不知道如何发图片，所以做了以下说明，你看能否理解：

源域训练集X→y
1 2 3 → 100
5 6 7 → 200
目标域训练集X’→y’
8 9 4 → 400
测试集X‘’→y‘’
2 4 1 → ？

**Comment by Bin-Cao** [comment]
您方便的话可以通过邮箱联系我，我们通过微信联系交流

**Comment by qinhaohcen** [comment]
好的，这是我的微信



---- 回复的原邮件 ----
| 发件人 | 曹斌 | Bin ***@***.***> |
| 日期 | 2023年04月01日 11:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Bin-Cao/TrAdaboost] 请教一下，关于Two_stage_TrAdaboost_R2中exp6的内容 (Issue #2) |

您方便的话可以通过邮箱联系我，我们通过微信联系交流

**Comment by Bin-Cao** [comment]
您好，这个邮件是github代发的,不会显示个人邮箱信息，请您联系我的个人邮箱 ： binjacobcao@gmail.com
