### ISSUE TITLE
大神 我想问下你输入的数据都是怎么得来的呀？

### ISSUE THREAD

**Issue by anglgn** [Bin-Cao/TrAdaboost#3]
想问下有什么代码可以处理中文数据得到输入的矩阵，tradaboost又是否可改成多分类问题？

**Comment by Bin-Cao** [comment]
您好：
（1）：例子中的输入的数据均是我们课题组实验数据或公开文献收集的数据，是我在工作中积累的数据的一部分（更多数据的不能公开分享，抱歉）。
（2）：处理中文数据得到输入的矩阵是可以的，我本人不做自然语言处理，不能为您提供详细代码和中肯建议，抱歉。
（3）：tradaboost可以改成多分类，通过基学习器做多分类的输出，按照tradaboost更新数据权重和计算基学习器权重，即可得做多分类任务。基学习器不局限于本例中的CART tree, 实际上在 two_stage中，我提供了通过自抽样改变数据权重的代码，可以使用该方法改变任意基学习器的数据权重。

希望以上回答对您有帮助！

**Comment by anglgn** [comment]
感谢！
